version: "3.7"

networks:
  default:
    external:
      name:
        local

services:
  postgres:
    image: postgres:14
    container_name: sepaket_postgres
    ports:
      - 3111:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image:  "adminer"
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
    ports:
      - "6379"
