version: "3.7"

networks:
  default:
    external:
      name:
        local

services:
  sepaket_api:
    build: .
    env_file: .env
    volumes:
      - ./public/file:/home/express/sepaket/public/file
      - /home/express/sepaket/public/file/seller
      - /home/express/sepaket/public/file/admin
    ports:
      - 3000:3000
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
    command: "npm run start"
