const jneStatus = {
  PROCESSED: [
    '102', // JNE - CLEARANCE PROCESS
    '307', // JNE - WAJIB DILAKUKAN PEMERIKSAAN FISIK OLEH BEA CUKAI
    '403', // JNE - DISETUJUI PENGELUARAN OLEH BEA CUKAI
    '914', // JNE - DITETAPKAN OLEH PEJABAT BEA CUKAI SEBAGAI BADAN USAHA, HARGA BARANG MELEBIHI USD 1,500
    'BI1', // JNE - RECEIVED AT WAREHOUSE
    'BI2', // JNE - RECEIVED AT INBOUND STATION
    'BI3', // JNE - WITH DELIVERY COURIER
    'CR3', // JNE - SHIPMENT PICKED UP BY CONSIGNEE AS REQUESTED BY SHIPPER/CONSIGNEE
    'CR5', // JNE - SHIPMENT BEING HELD AS SHIPPERS REQUEST
    'HL3', // JNE - WAITING FOR NEXT DEPARTURE SCHEDULE TO FINAL DESTINATION
    'HL4', // JNE - HOLD - MENUNGGU PEMBAYARAN COD
    'IP1', // JNE - RECEIVED AT WAREHOUSE
    'IP2', // JNE - RECEIVED AT INBOUND STATION
    'IP3', // JNE - WITH DELIVERY COURIER
    'KRK', // JNE - KANTOR/RUMAH KOSONG
    'KRP', // JNE - KANTOR/RUMAH PINDAH ALAMAT
    'KRT', // JNE - KANTOR TUTUP
    'MP', // JNE - MISSED PICKUP
    'NT', // JNE - NOT TIME DELIVERY
    'OC', // JNE - DESTINATION CORRECTION
    'OMX', // JNE - PROCESSED AT SORTING CENTER
    'OP1', // JNE - RECEIVED AT SORTING CENTER
    'OP2', // JNE - PROCESSED AT SORTING CENTER
    'OP3', // JNE - SHIPMENT FORWARDED FROM TRANSIT CITY TO DESTINATION CITY
    'OP4', // JNE - SHIPMENT FORWARDED FROM TRANSIT CITY TO DESTINATION CITY
    'OPX', // JNE - RECEIVED AT SORTING CENTER [CITY)
    'PR1', // JNE - KIRIMAN BELUM SIAP DAN TIDAK BISA DI PICK UP
    'PU0', // JNE - SHIPMENT PICKED UP BY JNE COURIER
    'PU1', // JNE - PICKED UP BY COURIER
    'PU2', // JNE - SHIPMENT PICKED UP BY COURIER WITHOUT CONNOTE (ONLY APPLY FOR CORPPORATE CUSTOMERS)
    'R14', // JNE - CHANGE SCHEDULE
    'RC1', // JNE - SHIPMENT RECEIVED BY JNE COUNTER OFFICER AT
    'REQ', // JNE - PICK UP REQUEST
    'S01', // JNE - PICK UP SUCCESS
    'T01', // JNE - SHIPMENT ALREADY UPLOADED, BUT UNLOADED DUE TO CERTAIN REASON
    'T02', // JNE - SHIPMENT CAN NOT BE LOADED DUE TO CARRIER ALREADY OVER CAPACITY
    'T03', // JNE - SHIPMENT BEING HELD AT TRANSIT CITY
    'T04', // JNE - SHIPPING ACTIVITY SUSPENDED TEMPORARY FOR CERTAIN REASON (BY REGULATION)
    'T05', // JNE - SHIPMENT CARRIED OVER TO OTHER AIPORT DUE TO TECHNICAL PROBLEM
    'T06', // JNE - DEPARTURE SCHEDULE BEING CANCELLED
    'T07', // JNE - AIRPLANE RETURN TO BASE DUE TO CERTAIN REASON (SAFETY,BAD WEATHER,ETC)
    'T08', // JNE - AIRPLANE DIVERTED NOT TO DESTINATION AIRPORT, DUE TO CERTAIN REASON (SAFETY,BAD WEATHER,ETC)
    'T09', // JNE - DELAY OF SCHEDULE DEPARTURE
    'T10', // JNE - MISROUTE
    'T11', // JNE - TRANSPORTATION MODES BACK TO ORIGIN STATION
    'T12', // JNE - SWITCH OF DESTINATION TO ANOTHER STATION
    'T13', // JNE - DELAY OF CARRIER DEPARTURE SCHEDULE
    'T14', // JNE - CHANGE OR CARRIER DEPARTURE SCHEDULE
    'TP1', // JNE - RECEIVED AT ORIGIN GATEWAY
    'TP2', // JNE - DEPARTED FROM ORIGIN GATEWAY
    'TP3', // JNE - RECEIVED AT TRANSIT
    'TP4', // JNE - DEPARTED FROM TRANSIT
    'TP5', // JNE - RECEIVED AT DESTINATION GATEWAY
    'U05', // JNE - NOBODY AT HOME / OFFICE TO RECEIVE SHIPMENT
    'U09', // JNE - OFFICE CLOSED DURING WEEKEND/NATIONAL HOLIDAY
    'U23', // JNE - CLOSED ON WEEKEND (COD SHIPMENT)
    'U24', // JNE - WAITING FOR COD AMOUNT CONFIRMATION
    'U25', // JNE - WAITING COD PAYMENT FROM CONSIGNEE
    'UB1', // JNE - LOCKER POP BOX FULL
    'UB2', // JNE - OVER 3 DAYS IN LOCKER BOX
    'WH1', // JNE - RECEIVED AT UNDEL WAREHOUSE DESTINATION
    'WH2', // JNE - RECEIVED AT UNDEL DESTINATION TO RETURN PROCESS
    'WH3', // JNE - RECEIVED AT UNDEL DESTINATION TO REDELIVERY PROCESS
    'WH5', // JNE - RECEIVED AT WAREHOUSE HOLD DESTINATION
  ],
  DELIVERED: [
    'D01', // JNE - DELIVER
    'D02', // JNE - DELIVER
    'D03', // JNE - DELIVER
    'D04', // JNE - DELIVER
    'D05', // JNE - DELIVER
    'D06', // JNE - DELIVER
    'D07', // JNE - DELIVER
    'D08', // JNE - DELIVER
    'D09', // JNE - DELIVER
    'D10', // JNE - DELIVER
    'D11', // JNE - DELIVER
    'D12', // JNE - DELIVER
    'DB1', // JNE - DELIVER
    'DB2', // JNE - DELIVER
  ],
  CANCELED: [
    'CR2', // JNE - SHIPMENT CANCELED AS SHIPPERS REQUEST
    'F05', // JNE - CANCEL ORDER
  ],
  RETURN_TO_SELLER: [
    'CR6', // JNE - UNDELIVERY
    'CR7', // JNE - RETURN SHIPMENT BEING HELD AT ORIGIN
    'CR8', // JNE - RETURN TO MARKETPLACE
    'D15', // JNE - RETURN,
    'D16', // JNE - RETURN,
    'PR2', // JNE - TIDAK ADA PENGIRIMAN PAKET
    'R01', // JNE - RETURN SHIPMENT TO
    'R02', // JNE - RETURN SHIPMENT TO
    'R03', // JNE - RETURN SHIPMENT TO
    'R04', // JNE - RETURN SHIPMENT TO
    'R05', // JNE - RETURN SHIPMENT TO
    'R06', // JNE - RETURN SHIPMENT TO
    'R07', // JNE - RETURN SHIPMENT TO
    'R08', // JNE - RETURN SHIPMENT TO
    'R09', // JNE - RETURN SHIPMENT TO
    'R10', // JNE - RETURN SHIPMENT TO
    'R11', // JNE - RETURN SHIPMENT TO
    'R12', // JNE - RETURN SHIPMENT TO
    'R13', // JNE - RETURN SHIPMENT TO
    'R24', // JNE - RETURN SHIPMENT TO
    'R25', // JNE - RETURN SHIPMENT TO
    'R26', // JNE - RETURN SHIPMENT TO
    'RC2', // JNE - SHIPMENT RECEIVED AT JNE ORIGIN OPERATIONAL OFFICE (ONLY APPLY FOR PROJECTS SHIPMENT)
  ],
  PROBLEM: [
    '305', // JNE - DIBUTUHKAN DOKUMEN PENDUKUNG DARI PENERIMA
    '915', // JNE - NILAI FOB YANG DITETAPKAN OLEH PEJABAT BEA CUKAI TIDAK MEMENUHI KRITERIA UNTUK DIAJUKAN SEBAGAI CN H.
    'CR7', // JNE - RETURN SHIPMENT BEING HELD AT ORIGIN
    'DP3', // JNE - TIDAK MASUK AREA LAYANAN YES (OUT OF YES AREA)
    'DP4', // JNE - PERUBAHAN ALAMAT PENERIMA
    'DP5', // JNE - COURIER ACCIDENT
    'F06', // JNE - FORCE MAJEURE
    'FOM', // JNE - AKSES JALAN TIDAK BISA DILALUI KARENA FORCE MAJEUR
    'HL1', // JNE - SHIPMENT IS BEING HELD DUE TO MISMATCH DATA
    'HL2', // JNE - HOLD - TIDAK LOLOS X-RAY
    'OS', // JNE - OUT OF YES SERVICE AREA
    'PS1', // JNE - SHIPMENT PROBLEM
    'PS4', // JNE - SHIPMENT PROBLEM
    'U01', // JNE - INCOMPLETE CONSIGNEE ADDRESS
    'U02', // JNE - COMPLETE ADDRESS, BUT CONSIGNEE UNKNOWN
    'U03', // JNE - HOME/OFFICE ADDRESS ALREADY MATCH,BUT CONSIGNEE MOVED
    'U04', // JNE - UNABLE TO DELIVER
    'U06', // JNE - CONSIGNEE REFUSE TO RECEIVE SHIPMENT
    'U07', // JNE - NOT INHABITED
    'U08', // JNE - CONSIGNEE REFUSE TO PAY COD SHIPMENT/SHIPMENT FEE
    'U10', // JNE - NO ACCESS DUE TO FORCE MAJEURE
    'U11', // JNE - SHIPMENT PROBLEM
    'U12', // JNE - SHIPMENT PROBLEM
    'U13', // JNE - SHIPMENT PROBLEM
    'U14', // JNE - SHIPMENT PROBLEM
    'U21', // JNE - RECIPIENTS REFUSED TO RECEIVE COD SHIPMENT (NOT ORDER)
    'U22', // JNE - CLOSED/NOT AVAILABLE (COD SHIPMENT)
    'WH4', // JNE - DESTROY SHIPMENT
    'X1', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK DANGEROUS GOODS
    'X10', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK -DOCUMENTS ARE NOT COMPLETE
    'X2', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-LIVE ANIMAL
    'X31', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-PERISHABLE
    'X32', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-PERISHABLE
    'X4', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-HUMAN REMAINS
    'X5', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK-VALUABLE GOODS
    'X6', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK-STRONGLY SMELLING GOODS
    'X71', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-LIVE PLANT
    'X72', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-LIVE PLANT
    'X8', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK SPECIAL CARGO-SWALLOW BIRD NEST
    'X9', // JNE - SHIPMENT BEING HELD DUE TO DID NOT PASS X-RAY CHECK -FORBIDDEN
  ],
};

module.exports = jneStatus;
