const sapStatus = {

  WAITING_PICKUP: [
    'ENTRI (SEDANG DI PICKUP)',
    'ENTRI (PENDING PICKUP)',
    'ENTRI (SEDANG PICKUP ULANG)',
  ],

  PROCESSED: [
    'PICKED UP ',
    'ENTRI VERIFIED ',
    'MANIFEST OUTGOING',
    'OUTGOING SMU',
    'INCOMING',
    'DELIVERY',
    'OUTGOING RETURN',
    'INCOMING RETURN',
    'DELIVERY RETURN',
  ],
  DELIVERED: [
    'POD - DELIVERED',
  ],
  CANCELED: [
    'VOID PICKUP',
  ],
  RETURN_TO_SELLER: [
    'SHIPMENT RETURN TO CLIENT',
  ],
  PROBLEM: [
    'POD - UNDELIVERED',
  ],
};

module.exports = sapStatus;
