require('dotenv').config();

module.exports = {
  development: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    logging: process.env.DB_DEBUG === 'true',
    migrationStorageTableName: 'migration',
    // pool : {
    //   max: parseInt(process.env.DB_POOL_MAX, 10),
    //   min: parseInt(process.env.DB_POOL_MIN, 10),
    //   acquire: parseInt(process.env.DB_POOL_ACQUIRE, 10),
    //   idle: parseInt(process.env.DB_POOL_IDLE, 10),
    // },
  },
  test: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    logging: process.env.DB_DEBUG === 'true',
    migrationStorageTableName: 'migration',
  },
  staging: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    logging: process.env.DB_DEBUG === 'true',
    migrationStorageTableName: 'migration',
  },
  production: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    logging: process.env.DB_DEBUG === 'true',
    migrationStorageTableName: 'migration',
    // pool : {
    //   max: parseInt(process.env.DB_POOL_MAX, 10),
    //   min: parseInt(process.env.DB_POOL_MIN, 10),
    //   acquire: parseInt(process.env.DB_POOL_ACQUIRE, 10),
    //   idle: parseInt(process.env.DB_POOL_IDLE, 10),
    // },
  },
};
